@baseURL = http://localhost:7100/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFkYTM4ZjU3NDJiMDQ5MmNhMzFhOWYiLCJpYXQiOjE3NDY3NzI5ODAsImV4cCI6MTc0OTM2NDk4MH0.lbDbN9phkrRqYCgkd6ROW_4WrazLqBItX43dbkjxJF4

### 创建角色
POST {{baseURL}}/role/create
Content-Type: application/json
Authorization: {{token}}

{
  "name": "角色22",
  "description": "角色描述",
  "departments":[
    "681cb4cb04414b740f0a948b",
    "681cb4cf04414b740f0a948d"
  ]
}

### 查询单个角色
GET {{baseURL}}/role/get/681caa1a0b18e9828e7cb520
Authorization: {{token}}

### 查询所有角色
POST {{baseURL}}/role/list
Content-Type: application/json
Authorization: {{token}}

{
  "page":1,
  "limit":10
}
